---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-olm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keda-olm-operator
  template:
    metadata:
      labels:
        name: keda-olm-operator
    spec:
      serviceAccountName: keda-olm-operator
      containers:
        - name: keda-olm-operator
          image: ghcr.io/kedacore/keda-olm-operator:main
          args:
            - --leader-elect
            - --zap-log-level=info
            - --zap-encoder=console
            - --zap-time-encoding=rfc3339
          command:
            - /manager
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 25
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 20
          env:
            - name: KEDA_OPERATOR_IMAGE
              value: quay.io/joelsmith/keda:2.10.1
            - name: KEDA_METRICS_SERVER_IMAGE
              value: quay.io/joelsmith/keda-metrics-apiserver:2.10.1
            - name: KEDA_ADMISSION_WEBHOOKS_IMAGE
              value: quay.io/joelsmith/keda-admission-webhooks:2.10.1
            - name: WATCH_NAMESPACE
              value: keda
